### ISSUE TITLE
VDOT, VDOTW, VCROSS functions

### ISSUE THREAD

**Issue by glenneng** [jasondegraw/View3D#3]
The functions VDOT, VDOTW, VCROSS appear in View3D. The purpose of these functions seems clear enough, they are not defined in the View3D source. Perhaps they are defined as part of a standard library?

Can anyone tell me where these functions are defined?

Thanks.

**Comment by jasondegraw** [comment]
Those are actually preprocessor defines:

https://github.com/jasondegraw/View3D/blob/master/src/view3d.h#L84

**Comment by glenneng** [comment]
Thanks very much. I thought I had searched all the header files, but apparently not. Thanks again.
