### ISSUE TITLE
View Factor from Points

### ISSUE THREAD

**Issue by ocni-dtu** [jasondegraw/View3D#4]
Hey,

Is it possible to calculate the view factor from a point to a given set of surfaces? 
I can't find anything about it in the documentation, but I seem to recall it been described in the original paper.

Cheers!
Christian

**Comment by jasondegraw** [comment]
@ocni-dtu Yes and no. The single area integration function `View1AI` (in viewobs.c) is computing an overall view factor from a sum of differential surface to polygon view factors. That isn't exactly the view factor to a surface from a point, but it's a close as I can find from the papers that you might be referring to. I believe it is possible to use `V1AIpart` to compute a "point" to surface view factor, but the main driver program isn't set up to report that, and obstructions would need to be handled, and so on.

If you're looking for the view factor from a point in space (and not a point on a surface) to surfaces, then View3D won't do that. For that problem, there are non-iterative geometrical methods that are preferable.

Does that help?

**Comment by ocni-dtu** [comment]
Thanks for the explanation @jasondegraw!
Could you recommend any software, which uses the "non-iterative geometrical methods" you speak of?

**Comment by jasondegraw** [comment]
Hmmm, I could have sworn I responded to this months ago. No, I'm not aware of any software that use the geometric methods. For points, it's generally possible to cobble together closed-form calculations that at least approximate the view factor.
